name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Build and run tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Git
      run: |
        git config --global url."https://user:${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Process test results
      if: ${{ success() || failure() }}
      shell: pwsh
      run: ./eng/process-test-results.ps1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
