name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run release script
        shell: pwsh
        run: ./eng/release.ps1
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
